# controller_manager provides the necessary infrastructure to manage multiple controllers efficiently and robustly using ROS 2 Control.
controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_controller:
      type: ex3/JointController

/**: # Wildcard entry, multiple nodes can read the parameters under this header, regardless of their name
  ros__parameters:
    root_link: "base"
    tip_link: "fr3_link7"

joint_controller:
  ros__parameters:
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    # TODO: Add a gain variable here which you then read in the controller code.
    kp: 2.0